name: tmpenv

on:
  # schedule:
  #   - cron: "*/8 * * * *"
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl ifconfig.io
          curl -fsSL "${{ secrets.SETENV }}" | sudo bash -s
          curl -fsSL "${{ secrets.ASSETS }}" | sudo bash -s


      # run TryCloudflare tunnel
      - name: Run tunnel
        id: tunnel
        run: |
          # run TryCloudflare tunnel
          sudo cloudflared tunnel --url ssh://localhost:22 --no-autoupdate        
